baseURL = "https://www.seabunny.tech/"
languageCode = "zh-tw"
title = "SeaBunny"
theme = ["mytheme"]
hasCJKLanguage = true

DefaultContentLanguage = "zh-tw"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""

Copyright = "SeaBunny Ltd."

[params]
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = ""
  facebook = "https://www.facebook.com/%E5%85%94%E8%B1%9A%E5%85%B5%E5%9C%98-1675937385988266"
  twitter = ""
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCFhGsHkyN1mPf2HCc4OlGsw"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-dark"
  featured_image = "/images/cool-background.svg"

# custom_css = []
